"""initial migration

Revision ID: 7b7576391de1
Revises: 
Create Date: 2026-08-23 16:36:56.276291

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b7576391de1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    if is_sqlite:
        # SQLite-compatible version - simpler syntax
        op.execute("""
            CREATE TABLE products (
                product_id VARCHAR NOT NULL,
                tenant_id VARCHAR NOT NULL DEFAULT 'tenant_demo',
                product_name VARCHAR NOT NULL,
                attributes_json TEXT NOT NULL DEFAULT '{}',
                quality_json TEXT NOT NULL DEFAULT '{}',
                classification_json TEXT,
                related_json TEXT NOT NULL DEFAULT '{}',
                sources_json TEXT NOT NULL DEFAULT '[]',
                review_log_json TEXT NOT NULL DEFAULT '[]',
                created_at DATETIME NOT NULL DEFAULT (datetime('now')),
                updated_at DATETIME NOT NULL DEFAULT (datetime('now')),
                version INTEGER NOT NULL DEFAULT 1,
                PRIMARY KEY (product_id, tenant_id)
            )
        """)
        
        op.execute("""
            CREATE TABLE customer_reliability (
                id VARCHAR NOT NULL,
                tenant_id VARCHAR NOT NULL DEFAULT 'tenant_demo',
                customer_id VARCHAR NOT NULL DEFAULT 'global',
                source_type VARCHAR NOT NULL,
                alpha FLOAT NOT NULL DEFAULT 1.0,
                beta FLOAT NOT NULL DEFAULT 1.0,
                updated_at DATETIME NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (id)
            )
        """)
        
        op.execute("CREATE INDEX ix_products_product_id ON products(product_id)")
        op.execute("CREATE INDEX ix_products_tenant_id ON products(tenant_id)")
        op.execute("CREATE INDEX ix_customer_reliability_tenant_id ON customer_reliability(tenant_id)")
        op.execute("CREATE INDEX ix_customer_reliability_source_type ON customer_reliability(source_type)")
    else:
        # PostgreSQL version with JSON types
        op.create_table(
            'products',
            sa.Column('product_id', sa.String(), nullable=False),
            sa.Column('tenant_id', sa.String(), nullable=False, server_default='tenant_demo'),
            sa.Column('product_name', sa.String(), nullable=False),
            sa.Column('attributes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
            sa.Column('quality_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
            sa.Column('classification_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column('related_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
            sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
            sa.Column('review_log_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
            sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
            sa.PrimaryKeyConstraint('product_id', 'tenant_id', name='products_pkey')
        )
        op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
        op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
        
        op.create_table(
            'customer_reliability',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('tenant_id', sa.String(), nullable=False, server_default='tenant_demo'),
            sa.Column('customer_id', sa.String(), nullable=False, server_default='global'),
            sa.Column('source_type', sa.String(), nullable=False),
            sa.Column('alpha', sa.Float(), nullable=False, server_default='1.0'),
            sa.Column('beta', sa.Float(), nullable=False, server_default='1.0'),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
            sa.PrimaryKeyConstraint('id', name='customer_reliability_pkey')
        )
        op.create_index(op.f('ix_customer_reliability_tenant_id'), 'customer_reliability', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_customer_reliability_source_type'), 'customer_reliability', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    if is_sqlite:
        op.execute("DROP INDEX IF EXISTS ix_customer_reliability_source_type")
        op.execute("DROP INDEX IF EXISTS ix_customer_reliability_tenant_id")
        op.execute("DROP TABLE IF EXISTS customer_reliability")
        op.execute("DROP INDEX IF EXISTS ix_products_tenant_id")
        op.execute("DROP INDEX IF EXISTS ix_products_product_id")
        op.execute("DROP TABLE IF EXISTS products")
    else:
        op.drop_index(op.f('ix_customer_reliability_source_type'), table_name='customer_reliability')
        op.drop_index(op.f('ix_customer_reliability_tenant_id'), table_name='customer_reliability')
        op.drop_table('customer_reliability')
        op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
        op.drop_index(op.f('ix_products_product_id'), table_name='products')
        op.drop_table('products')
    # ### end Alembic commands ###